### ISSUE TITLE
As an examiner, I want to know the different technologies available related to automatic deployment

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/tfg#2]

**Comment by harvestcore** [comment]
closed here https://github.com/harvestcore/tfg/pull/1

**Comment by JJ** [comment]
You should never close an issue without proving that it does what it should; also, every issue should include acceptance criterium. More extensive description of the issue, and also how the PR achieves that would be also needed.

**Comment by JJ** [comment]
> closed here #1

You should always close with a commit. You can create the commit when you merge a PR.
