### ISSUE TITLE
DOC: Provision

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/tfg#20]
Once investigated the ways to do provision management (libraries, concepts, best practices, tools, etc) in Python add that knowledge to the documentation.

**Comment by JJ** [comment]
A user story should describe high-level results in a black-box matter, not the tasks needed to achieve them. Why do you want to run provision scripts? What's the result you want to achieve? If you use tasks to describe user stories, acceptance criterium is simply the realization of the task. If you use the desired behavior, the acceptance test would be to check that the objective has actually been achieved.

**Comment by JJ** [comment]
Also, this is not a documentation issue, it's a development issue. Documentation should simply describe decisions taken in development. But if it was a documentation issue, it shouldn't be in the "backend" milestone.

**Comment by JJ** [comment]
So #21 does not have anything to with documentation, after all...
