### ISSUE TITLE
DEV: Provision execution

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/tfg#22]
Related to [20](https://github.com/harvestcore/tfg/issues/20)

Endpoints to execute provision scripts
- GET: Info about the execution
- POST: Run execution
- DELETE: Stop/remove execution (tbd more in depth)

Also add:
- Unit tests
- Documentation about endpoints (input/output data, etc)

**Comment by JJ** [comment]
When you say "documentation", you mean "research", as in "research different ways to do something"?

**Comment by harvestcore** [comment]
@JJ Yes, I mean research. Probably it is not the best term to describe what I mean to do. During the development of both front and backend I've been taking notes of the researches done and also about all decissions I've made. The next step will be to create issues to integrate all that content into the documentation.
