### ISSUE TITLE
Dockerize the backend

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/tfg#37]
As a user I want to be able to use the backend API within a docker container so I don't need to install it natively in all the needed machines.

The backend must be dockerized and must be fully configurable via environment variables.

**Comment by JJ** [comment]
This is such an important issue, with lots of commits, that it should really be more descriptive. It's clear to you what you want, but it's not clear at all how you achieve that. Also, as stated above, an issue should describe behavior, not the task you want. By describing it, it's not clear at all what kind of behavior of the system you want to observe.

**Comment by harvestcore** [comment]
Closed on https://github.com/harvestcore/tfg/pull/58
