### ISSUE TITLE
Add missing deploy tests

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/tfg#50]
As a developer I want unit tests to ensure that all deploy operations work as expected.

Currently not all operations are tested, so it is needed to add one or more test for each deploy operation before the backend can be released.

**Comment by JJ** [comment]
This shouldn't be an issue. There should be *all* deploy tests. You should describe what you want to achieve with the deployment, and from them write tests that achieve it.

**Comment by harvestcore** [comment]
You're right, this should not be an issue. It was more like a self-reminder to add some operation tests I missed in a past issue/PR.

**Comment by harvestcore** [comment]
But also, it is not descriptive enough, so it needs a refactor.
