### ISSUE TITLE
Make milestones descriptive.

### ISSUE THREAD

**Issue by JJ** [harvestcore/tfg#54]
The milestones are described by a single word. They should ideally be

* More atomic "Frontend" and "backend" probably need a lot more granularity.
* Describe the actual milestone.  "When this product is ready, we'll know we've finished the product". This should include an acceptance test.
* Have a date attached to them. That will help you assess the time needed to to them.

First step is to really expand the milestones that exist right now. Then, probably add more as they become what they should really be.

**Comment by harvestcore** [comment]
Completely agree with your comments @JJ . Currently the milestones do not have the correct structure and they have no info attached at all, so it is quite ambiguous trying to understand its meaning. I will rewrite them and also remove useless ones + add due date.

I will also ping you here as soon as I finish so you can double check the milestones if you want to.

**Comment by JJ** [comment]
You probably can close this one when you show, in the report, how you've made them descriptive.
