### ISSUE TITLE
Issues should be descriptive.

### ISSUE THREAD

**Issue by JJ** [harvestcore/tfg#55]
Commits describe what you have done. issues should describe what you want to achieve, and how does that contribute to the milestone. 
Also, milestones are milestones, not places to hang out issues to dry. They should be hierarchical, as in "I get to this milestone, then I get to that one..."

**Comment by harvestcore** [comment]
Agreed. The issues are not descriptive enough, so I will check all issues (open and closed ones) and rewrite them/add more info if needed.

Same as [here](https://github.com/harvestcore/tfg/issues/54#issuecomment-607448376) @JJ, you are right about the milestones. I will work on them and then ping you here.

**Comment by JJ** [comment]
[Still not descriptive](https://github.com/harvestcore/tfg/milestone/5). You are not saying what's needed for the frontend to satisfy user's needs. You're just saying common things that are applicable to all frontends.
