### ISSUE TITLE
Admin panel to manage users

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/tfg#82]
As an administrator user I want to be able to manage users in the frontend, so I can see, create, edit and delete them. This panel should be only accessible to administrator users.

To do so:
- Create new component.
- Create dialog to add new users or clients.
- Create dialog to display an individual user or client.
- Display data in a list -> check designs.

Also create panel so each user can manage its own user data.

* Important: Keep it simple

**Comment by JJ** [comment]
"user" managing "users"? Are there different kind of users?

**Comment by harvestcore** [comment]
@JJ Woops, that's a mistake, I wanted to say "As an administrator user..."

**Comment by harvestcore** [comment]
Closed on #96
