### ISSUE TITLE
Ensure that the frontend works as expected

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/tfg#92]
As a user I want a stable version of the frontend before start using it.

- Ensure that the frontend has no weird behavior or malfunctionatilities.
- Review all documentation and workflows.
- Check the docker container generated, and also the docker-compose.
- Clean obsolete code.
- Add integration tests workflow.

**Comment by JJ** [comment]
This asks for integration tests, using Cypress or something similar.

**Comment by harvestcore** [comment]
@JJ Sure, I will add them as well.

**Comment by harvestcore** [comment]
Closed on https://github.com/harvestcore/tfg/pull/98
